export const TODO_CARD_ADD = 'TODO_CARD_ADD'
export const TODO_CARD_SORT = 'TODO_CARD_SORT'

export const TODO_CARD_ITEM_ADD = 'TODO_CARD_ITEM_ADD'


export const TODO_MAIN_ADD = 'TODO_MAIN_ADD'
export const TODO_MAIN_DELETE = 'TODO_MAIN_DELETE'
